NAME = rush-02
SRC = ft_isnumber.c ft_file_size.c ft_znach.c ft_putstr.c ft_strcmp.c list.c main.c
CC = gcc
CFLAGS = -Wall -Wextra -Werror

.PHONY:	all clean fclean

all: $(NAME)

$(NAME): $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)

clean:		
	rm $(NAME)

fclean: clean


